# Generated by Django 3.2.4 on 2021-06-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='fin_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.fy'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.classroom'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.student'),
        ),
        migrations.AddField(
            model_name='studentcomments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.student'),
        ),
        migrations.AddField(
            model_name='studentpersonalinfo',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.student'),
        ),
        migrations.AddField(
            model_name='teacherpersonalinfo',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.teacher'),
        ),
    ]
