# Generated by Django 3.2.4 on 2021-06-20 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0002_auto_20210620_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentComments',
            new_name='StudentComment',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='fin_year',
            new_name='financial_year',
        ),
        migrations.AddField(
            model_name='classroom',
            name='meet_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fy',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fees_type', models.IntegerField(choices=[(0, 'Tution Fees'), (1, 'Kit Amount'), (2, 'Event Fees'), (3, 'Registration Fees'), (4, 'Damages'), (5, 'Others')])),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('amountINR', models.IntegerField()),
                ('classroom', models.ForeignKey(help_text='Select Only ONE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.classroom')),
                ('financial_year', models.ForeignKey(help_text='Select Only ONE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.fy')),
                ('student', models.ForeignKey(help_text='Select Only ONE', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_remaining', models.IntegerField()),
                ('completed', models.IntegerField(choices=[(1, 'Completed'), (0, 'Pending')], default=0)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('fees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.fees')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
