# Generated by Django 3.2.4 on 2021-06-20 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0003_auto_20210620_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fees',
            new_name='Fee',
        ),
        migrations.RenameField(
            model_name='amount',
            old_name='fees',
            new_name='fee',
        ),
    ]
