# Generated by Django 3.2.4 on 2021-08-18 20:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0005_auto_20210814_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='weight',
        ),
        migrations.AddField(
            model_name='student',
            name='weightKG',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coreengine.fy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.date(2021, 8, 18)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='heightCM',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
