# Generated by Django 3.2.4 on 2021-08-28 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0007_alter_classroom_timetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.IntegerField(choices=[(2, 'Endsem'), (1, 'Midsem'), (0, 'UnitTest')])),
                ('status', models.IntegerField(choices=[(3, 'Closed'), (2, 'Completed'), (1, 'Started'), (0, 'Created')], default=0)),
                ('wightage', models.IntegerField(default=0)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.fy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='classroom',
            name='financial_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='coreengine.fy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('subject', models.IntegerField(choices=[(8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('marks', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=20)),
                ('result', models.IntegerField(blank=True, choices=[(1, 'Fail'), (0, 'Pass')], null=True)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='exams',
            field=models.ManyToManyField(blank=True, help_text='Select/Create all tests taken for this class', to='coreengine.Exam'),
        ),
    ]
