# Generated by Django 3.2.4 on 2021-08-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0008_auto_20210828_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammark',
            old_name='financial_year',
            new_name='exam',
        ),
    ]
