# Generated by Django 3.2.4 on 2021-09-19 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0010_auto_20210901_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AlterField(
            model_name='exammark',
            name='result',
            field=models.IntegerField(blank=True, choices=[(2, 'Absent'), (1, 'Fail'), (0, 'Pass')], null=True),
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(blank=True, null=True)),
                ('report_card', models.ImageField(blank=True, max_length=1000, null=True, upload_to='coreengine/report/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.student')),
            ],
        ),
    ]
