# Generated by Django 3.2.4 on 2022-01-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0011_auto_20210919_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('mon', models.IntegerField(choices=[(15, 'Grammer'), (14, 'Biology'), (14, 'Chemistry'), (14, 'Physics'), (13, 'Audio Visual'), (12, 'PT'), (11, 'Music'), (10, 'Games'), (9, 'Break'), (8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('tue', models.IntegerField(choices=[(15, 'Grammer'), (14, 'Biology'), (14, 'Chemistry'), (14, 'Physics'), (13, 'Audio Visual'), (12, 'PT'), (11, 'Music'), (10, 'Games'), (9, 'Break'), (8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('wed', models.IntegerField(choices=[(15, 'Grammer'), (14, 'Biology'), (14, 'Chemistry'), (14, 'Physics'), (13, 'Audio Visual'), (12, 'PT'), (11, 'Music'), (10, 'Games'), (9, 'Break'), (8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('thu', models.IntegerField(choices=[(15, 'Grammer'), (14, 'Biology'), (14, 'Chemistry'), (14, 'Physics'), (13, 'Audio Visual'), (12, 'PT'), (11, 'Music'), (10, 'Games'), (9, 'Break'), (8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('fri', models.IntegerField(choices=[(15, 'Grammer'), (14, 'Biology'), (14, 'Chemistry'), (14, 'Physics'), (13, 'Audio Visual'), (12, 'PT'), (11, 'Music'), (10, 'Games'), (9, 'Break'), (8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('sat', models.IntegerField(choices=[(15, 'Grammer'), (14, 'Biology'), (14, 'Chemistry'), (14, 'Physics'), (13, 'Audio Visual'), (12, 'PT'), (11, 'Music'), (10, 'Games'), (9, 'Break'), (8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreengine.classroom')),
            ],
        ),
    ]
