# Generated by Django 3.2.4 on 2022-01-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0013_auto_20220102_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
