# Generated by Django 3.2.4 on 2022-01-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0014_alter_classroom_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amount',
            name='total_amount',
            field=models.IntegerField(help_text='In Rupees'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.IntegerField(choices=[(13, 'Tenth'), (12, 'Ninth'), (11, 'Eighth'), (10, 'Seventh'), (9, 'Sixth'), (8, 'Fifth'), (7, 'Fourth'), (6, 'Third'), (5, 'Second'), (4, 'First'), (3, 'SR Kg'), (2, 'JR Kg'), (1, 'Nursery'), (0, 'Playschool')], default=1),
            preserve_default=False,
        ),
    ]
