# Generated by Django 3.2.4 on 2022-01-03 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0015_auto_20220102_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
