# Generated by Django 3.2.4 on 2022-01-07 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0016_promote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.AlterField(
            model_name='amount',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='amount',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='coreengine.fee'),
        ),
    ]
