# Generated by Django 3.2.4 on 2022-01-16 06:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0017_auto_20220107_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=200)),
                ('classroom', models.IntegerField(choices=[(9, 'Tenth'), (8, 'Ninth'), (7, 'Eighth'), (6, 'Seventh'), (5, 'Sixth'), (4, 'Fifth'), (3, 'Fourth'), (2, 'Third'), (1, 'Second'), (0, 'First')])),
                ('subject', models.IntegerField(choices=[(8, 'GeneralKnolowdge'), (7, 'Computer'), (6, 'Science'), (5, 'Maths'), (4, 'History'), (3, 'Geography'), (2, 'Marathi'), (1, 'Hindi'), (0, 'English')])),
                ('status', models.IntegerField(choices=[(2, 'Completed'), (1, 'Started'), (0, 'Created')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuizTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('team_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.quiz')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('question', models.CharField(max_length=500)),
                ('opt_a', models.CharField(max_length=200)),
                ('opt_b', models.CharField(max_length=200)),
                ('opt_c', models.CharField(max_length=200)),
                ('opt_d', models.CharField(max_length=200)),
                ('correct', models.CharField(choices=[('D', 'D'), ('C', 'C'), ('B', 'B'), ('A', 'A')], max_length=5)),
                ('report_card', models.ImageField(blank=True, max_length=1000, null=True, upload_to='coreengine/quiz/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coreengine.quizteam')),
            ],
        ),
    ]
