# Generated by Django 3.2.4 on 2022-01-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0018_question_quiz_quizteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='report_card',
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='templates/kbc/'),
        ),
    ]
