# Generated by Django 3.2.4 on 2022-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreengine', '0020_quiz_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='upload_questions',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='templates/kbc_bank/'),
        ),
    ]
