# Generated by Django 3.2.4 on 2021-08-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='templates/banner/'),
        ),
    ]
